### ISSUE TITLE
Error: contextify@0.1.15 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by lanc8** [blackjk3/react-form-builder#11]
I use Windows 7. But error while install. How can I fix it?

D:\MyCode\react-form-builder-master>npm install

> contextify@0.1.15 install D:\MyCode\react-form-builder-master\node_module
s\contextify
> node-gyp rebuild

D:\MyCode\react-form-builder-master\node_modules\contextify>if not defined
npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp
-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebu
ild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  contextify.cc
  win_delay_load_hook.cc
..\src\contextify.cc(150): error C2039: 'SetAccessCheckCallbacks': is not a mem
ber of 'v8::ObjectTemplate' [D:\MyCode\react-form-builder-master\node_modu
les\contextify\build\contextify.vcxproj]
  c:\users\wins7\.node-gyp\7.2.0\include\node\v8.h(4696): note: see declarati
  on of 'v8::ObjectTemplate'
..\src\contextify.cc(131): warning C4996: 'v8::Function::NewInstance': was decl
ared deprecated [D:\MyCode\react-form-builder-master\node_modules\contexti
fy\build\contextify.vcxproj]
  c:\users\wins7\.node-gyp\7.2.0\include\node\v8.h(3292): note: see declarati
  on of 'v8::Function::NewInstance'
..\src\contextify.cc(182): warning C4996: 'v8::Object::GetRealNamedProperty': w
as declared deprecated [D:\MyCode\react-form-builder-master\node_modules\c
ontextify\build\contextify.vcxproj]
  c:\users\wins7\.node-gyp\7.2.0\include\node\v8.h(2949): note: see declarati
  on of 'v8::Object::GetRealNamedProperty'
..\src\contextify.cc(209): warning C4996: 'v8::Object::GetRealNamedProperty': w
as declared deprecated [D:\MyCode\react-form-builder-master\node_modules\c
ontextify\build\contextify.vcxproj]
  c:\users\wins7\.node-gyp\7.2.0\include\node\v8.h(2949): note: see declarati
  on of 'v8::Object::GetRealNamedProperty'
..\src\contextify.cc(210): warning C4996: 'v8::Object::GetRealNamedProperty': w
as declared deprecated [D:\MyCode\react-form-builder-master\node_modules\c
ontextify\build\contextify.vcxproj]
  c:\users\wins7\.node-gyp\7.2.0\include\node\v8.h(2949): note: see declarati
  on of 'v8::Object::GetRealNamedProperty'
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` fail
ed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\MyCode\react-form-builder-master\node_modules\contextify
gyp ERR! node -v v7.2.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"
})
npm WARN react-bootstrap-native-slider@1.0.3 requires a peer of jquery@ but none
 was installed.
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.15 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the contextify@0.1.15 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs contextify
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\MyCode\react-form-builder-master\npm-debug.log

**Comment by blackjk3** [comment]
@lanc8 looks like it's an issue with node-gyp on windows. Maybe take a look at this issue from a different repo for guidance?  https://github.com/bevacqua/perfschool/issues/5

**Comment by lanc8** [comment]
Not solve my problem. And I tried to set up and use it in my project. I doesn't work at all: 
 var FormBuilder = require('react-forms-builder');
===> Can't found............ :(

**Comment by dwightware4** [comment]
I'm receiving this same error on OSX.

**Comment by mfrye** [comment]
Same here on OSX.

**Comment by VladimirJelincic** [comment]
I had the same node-gyp problem on Ubuntu 16.04 but this seemed to solve it:

1. Dropping down to Node LTS 6.11 (via nvm) solved the **contextify@0.1.15** error
2. Installing Canvas as noted  [here](https://www.npmjs.com/package/canvas) solved the **canvas@1.6.5** error

Now I can run the demo

**Comment by jaryway** [comment]
The follow packages are hard  to in installing:
1."jsdom": "^11.11.0",
2. "canvas": "^1.6.11",
3."node-sass": "^4.9.0"。
Install the above packages independently until they are successfully installed. And then your project will run well.

**Comment by Johnfredadams** [comment]
This is fixed the fork here: https://github.com/Kiho/react-form-builder
